routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('welcome');
Route::get('/home', 'HomeController@show')->name('home');

Route::view('scan', 'scan');

//Route::resource('threads', 'ThreadsController');

Route::group([
    'middleware' => ['admin']
], function () {
    Route::post('locked-threads/{thread}', 'LockedThreadsController@store')->name('locked-threads.store');
    Route::delete('locked-threads/{thread}', 'LockedThreadsController@destroy')->name('locked-threads.destroy');
});

Route::group([
    'prefix' => 'threads',
], function () {
    Route::get('search', 'SearchController@show');

    Route::get('/', 'ThreadsController@index')->name('threads');
    Route::get('{channel}/{thread}', 'ThreadsController@show');
    Route::patch('{channel}/{thread}', 'ThreadsController@update')->name('threads.update');
    Route::delete('{channel}/{thread}', 'ThreadsController@destroy');
    Route::get('{channel}', 'ThreadsController@index');

    Route::get('{channel}/{thread}/replies', 'RepliesController@index');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::post('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store');
        Route::delete('/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy');
        Route::post('{channel}/{thread}/replies', 'RepliesController@store');
    });
    Route::group([
        'middleware' => ['must-be-confirmed']
    ], function () {
        Route::post('/', 'ThreadsController@store')->middleware('must-be-confirmed');
        Route::get('create', 'ThreadsController@create')->middleware('must-be-confirmed');
    });
});

Route::group([
    'prefix' => 'replies',
    'middleware' => ['auth']
], function () {
    Route::delete('/{reply}', 'RepliesController@destroy')->name('replies.destroy');
    Route::patch('/{reply}', 'RepliesController@update');
    Route::post('/{reply}/favorites', 'FavoritesController@store');
    Route::delete('/{reply}/favorites', 'FavoritesController@destroy');
});

Route::post('/replies/{reply}/best', 'BestRepliesController@store')->name('best-replies.store');

Route::group([
    'prefix' => 'profiles',
    'middleware' => ['auth']
], function () {

    Route::get('/{user}', 'ProfilesController@show')->name('profile');

    Route::group([
        'middleware' => ['auth']
    ], function () {
        Route::get('/{user}/notifications', 'UserNotificationsController@index');
        Route::delete('/{user}/notifications/{notification}', 'UserNotificationsController@destroy');
    });
});

Route::get('/register/confirm', 'Auth\RegisterConfirmationController@index')->name('register.confirm');

app/Thread.php
<?php

namespace App;

use App\Events\ThreadReceivedNewReply;
use App\Filters\ThreadFilters;

use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use Stevebauman\Purify\Facades\Purify;
use Illuminate\Database\Eloquent\SoftDeletes;

class Thread extends Model
{
    use RecordsActivity, Searchable, SoftDeletes;

    protected $dates = ['deleted_at'];

	protected $guarded = [];

	protected $with = ['creator', 'channel'];

    protected $appends = ['isSubscribedTo'];

    protected $casts = [
        'locked' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($thread) {
            $thread->replies->each->delete();
        });

        static::created(function ($thread) {
            $thread->update(['slug' => $thread->title]);
        });
    }

    public function path()
    {
    	return "/threads/{$this->channel->slug}/{$this->slug}";
    }

    public function replies()
    {
    	return $this->hasMany(Reply::class);
    }

    public function getReplyCountAttribute()
    {
        return $this->replies()->count();
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }

    public function addReply($reply)
    {
        $reply = $this->replies()->create($reply);

        event(new ThreadReceivedNewReply($reply));

//        $this->notifySubscribers($reply);

		return $reply;
    }

    public function scopeFilter($query, ThreadFilters $filters)
    {
        return $filters->apply($query);
    }

    public function subscribe($userId = null)
    {
        $this->subscriptions()->create([
            'user_id' => $userId ?: auth()->id()
        ]);

        return $this;
    }

    public function unsubscribe($userId = null)
    {
        $this->subscriptions()
            ->where(['user_id' => $userId ?: auth()->id()])
            ->delete();
    }

    public function subscriptions()
    {
        return $this->hasMany(ThreadSubscription::class);
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->subscriptions()
            ->where('user_id', auth()->id())
            ->exists();
    }

    public function hasUpdatesFor($user = null)
    {
        $user = $user ?: auth()->user();

        $key = $user->visitedThreadCacheKey($this);

        return $this->updated_at > cache($key);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setSlugAttribute($value)
    {
        $slug = str_slug($value);

        if (static::whereSlug($slug)->exists()) {
            $slug = "{$slug}-" . md5($this->id);
        }

        $this->attributes['slug'] = $slug;
    }

    public function markBestReply(Reply $reply)
    {
        $this->update(['best_reply_id' => $reply->id]);
    }

    public function toSearchableArray()
    {
        return $this->toArray() + ['path' => $this->path()];
    }

    public function getBodyAttribute($body)
    {
        return Purify::clean($body);
    }
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable, SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'email',
    ];

    protected $casts = [
        'confirmed' => 'boolean',
        'is_admin' => 'boolean'
    ];

    public function getRouteKeyName()
    {
        return 'user_name';
    }

    public function threads()
    {
        return $this->hasMany(Thread::class)->latest();
    }

    public function lastReply()
    {
        return $this->hasOne(Reply::class)->latest();
    }

    public function activity()
    {
        return $this->hasMany(Activity::class);
    }

    public function read($thread)
    {
        cache()->forever(
            $this->visitedThreadCacheKey($thread),
            Carbon::now()
        );
    }

    public function confirm()
    {
        $this->confirmed = true;
        $this->confirmation_token = null;

        $this->save();
    }

    public function getAvatarPathAttribute($avatar)
    {
        return asset($avatar ? 'storage/' . $avatar : 'images/avatars/default.png');
    }

    public function visitedThreadCacheKey($thread)
    {
        return sprintf("users.%s.visits.%s", $this->id, $thread->id);
    }

    public function fullName()
    {
        return $this->first_name . ' ' . $this->last_name;
    }
}

app/Http/Controllers/ThreadsController.php
<?php

namespace App\Http\Controllers;

use App\Filters\ThreadFilters;
use App\Rules\Recaptcha;
use App\Rules\SpamFree;
use App\Thread;
use App\Channel;

use App\Trending;
use Illuminate\Http\Request;

class ThreadsController extends Controller
{
    /**
     * Create a new thread controller instance
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Channel $channel, ThreadFilters $filters, Trending $trending)
    {

        $threads = $this->getThreads($channel, $filters);

        if (request()->wantsJson()) {
            return $threads;
        }

        return view('threads.index', [
            'threads' => $threads,
            'trending' => $trending->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('threads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Recaptcha $recaptcha)
    {
        request()->validate([
            'title' => ['required', new SpamFree()],
            'body' => ['required', new SpamFree()],
            'channel_id' => 'required|exists:channels,id',
            'g-recaptcha-response' => ['required', $recaptcha]
        ]);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);

        if (request()->wantsJson()) {
            return response($thread, 201);
        }

        return redirect($thread->path())
            ->with('flash', 'Your thread has been published!');
    }

    /**
     * Display the specified resource.
     * @param  $channel
     * @param  \App\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function show($channel, Thread $thread, Trending $trending)
    {
        if (auth()->check()) {
            auth()->user()->read($thread);
        }

        $trending->push($thread);

        $thread->increment('visits_count');

        return view('threads.show', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function update($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->update(request()->validate([
            'title' => ['required', new SpamFree()],
            'body' => ['required', new SpamFree()]
        ]));

        return $thread;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);

        $thread->delete();

        if (request()->wantsJson()) {
            return response([], 204);
        }

        return redirect('/threads');
    }

    protected function getThreads(Channel $channel, ThreadFilters $filters)
    {

        $threads = Thread::latest()->filter($filters);

        if ($channel->exists) {

            $threads->where('channel_id', $channel->id);

        }
        
        return $threads->paginate(10);
    }
}

resources/views/threads/_list.blade.php
@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif
@forelse ($threads as $thread)
    <div class="card mb-3">
        <div class="card-header">
            <div class="level">
                <div class="flex">
                    <h4>
                        <a href="{{ $thread->path() }}">
                            @if (auth()->check() && $thread->hasUpdatesFor(auth()->user()))
                                <strong>
                                    {{ $thread->title }}
                                </strong>
                            @else
                                {{ $thread->title }}
                            @endif
                        </a>
                    </h4>

                    <h5>
                        Posted By: <a href="{{ route('profile', $thread->creator) }}">{{ $thread->creator->user_name }}</a>
                    </h5>

                </div>

                <a href="{{ $thread->path() }}">
                    <strong>{{ $thread->replies_count }} {{str_plural('reply', $thread->replies_count) }}</strong>
                </a>

            </div>
        </div>
        <div class="card-body">
            <div class="body">
                {!! $thread->body !!}
            </div>
        </div>
        <div class="card-footer">
            {{ $thread->visits_count }} Visits
        </div>
    </div>
@empty
    <p>There are no relevant results at this time.</p>
@endforelse

resources/views/threads/_thread_content.blade.php
<div class="card mb-3" v-if="editing">
    <div class="card-header">
        <div class="level">
            <input type="text" v-model="form.title" class="form-control"/>
        </div>
    </div>

    <div class="card-body">
        <div class="form-group">
            <wysiwyg name="body" v-model="form.body"></wysiwyg>
        </div>
    </div>

    <div class="card-footer">
        <div class="level">
            <button class="btn btn-primary btn-sm" @click="update">Update</button>
            <button class="btn btn-sm level-item" @click="resetForm">Cancel</button>
            @can ('update', $thread)
                <form action="{{ $thread->path() }}" method="POST" class="ml-auto">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit" class="btn btn-link">Delete Thread</button>
                </form>
            @endcan
        </div>
    </div>
</div>

<div class="card mb-3" v-else>
    <div class="card-header">
        <div class="level">
            <img src="{{  $thread->creator->avatar_path }}" alt="{{ $thread->creator->user_name }}" class="mr-1" width="50" height="50"/>
            <span class="flex">
                <a href="{{ route('profile', $thread->creator->user_name) }}">
                    {{ $thread->creator->user_name }}
                </a>
                posted:
                <span v-text="title"></span>
            </span>
        </div>
    </div>

    <div class="card-body" v-html="body"></div>

    <div class="card-footer" v-if="authorize('owns', thread)">
        <button class="btn btn-sm" @click="editing = true">Edit</button>
    </div>
</div>

resources/views/threads/create.blade.php
@extends('layouts.app')
@section('head')
    <script src='https://www.google.com/recaptcha/api.js'></script>
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header p">
                	Create a New Thread
                </div>

                <div class="panel-body p-1">
                	<form method="POST" action="/threads">

                		{{ csrf_field() }}

                		<div class="form-group p">
                			<label for="channel_id">Choose a Channel</label>
                		    <select name="channel_id" id="channel_id" class="form-control" required>

                		    	<option value="">
                		    		Choose a channel...
                		    	</option>

                		    	@foreach ($channels as $channel)

                		    	<option value="{{ $channel->id }}" {{ old('channel_id') == $channel->id ? 'selected' : ''}}>
                		    		{{ $channel->name }}
                		    	</option>

                		    	@endforeach
                		    </select>
                		</div>
                	
                		<div class="form-group p">
                			<label for="title">Title</label>
                		    <input type="text" class="form-control" name="title" id="title" value="{{ old('title') }}" required>
                		</div>

                		<div class="form-group p">
                			<label for="body">Body</label>
                            <wysiwyg name="body"></wysiwyg>
                		</div>

                        <div class="form-group p">
                            <div class="g-recaptcha" data-sitekey="{{ config('services.recaptcha.key') }}"></div>
                        </div>

                		<div class="form-group p">
                			<button type="submit" class="btn btn-default">Submit</button>
                		</div>

                	</form>

                	@if (count($errors))

                		<ul class="alert alert-danger">
                			@foreach ($errors->all() as $error)
	                			<li>{{ $error }}</li>
                			@endforeach
                		</ul>

                	@endif

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @include ('threads._list')
            {{ $threads->render() }}
        </div>
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-header">
                    Search
                </div>
                <div class="card-body">
                    <form method="GET" action="/threads/search">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." name="q" class="form-control">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </form>
                </div>
            </div>
            @if (count($trending))
            <div class="card mb-3">
                <div class="card-header">
                    Trending threads
                </div>
                <div class="card-body">
                    <ul class="list-group">
                    @foreach ($trending as $thread)
                        <li class="list-group-item">
                            <a href="{{ url($thread->path) }}">
                                {{ $thread->title }}
                            </a>
                        </li>
                    @endforeach
                    </ul>
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/threads/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <ais-index
                class="row"
                app-id="{{ config('scout.algolia.id') }}"
                api-key="{{ config('scout.algolia.key') }}"
                index-name="threads"
                query="{{ request('q') }}"
        >
            <div class="col-md-8">
                <ais-results>
                    <template slot-scope="{ result }">
                        {{--<p v-text="result.title">--}}
                        <li>
                            <a :href="result.path">
                                <ais-highlight :result="result" attribute-name="title"></ais-highlight>
                            </a>
                        </li>
                        {{--</p>--}}
                    </template>
                </ais-results>
            </div>
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-header">
                        Search
                    </div>
                    <div class="card-body">
                        <ais-search-box>
                            <ais-input placeholder="Find a thread..." :autofocus="true" class="form-control"></ais-input>
                        </ais-search-box>
                    </div>
                </div>
                <div class="card mb-3">
                    <div class="card-header">
                        Filter by Channel
                    </div>
                    <div class="card-body">
                        <ais-refinement-list attribute-name="channel.name"></ais-refinement-list>
                    </div>
                </div>
                @if (count($trending))
                <div class="card mb-3">
                    <div class="card-header">
                        Trending threads
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            @foreach ($trending as $thread)
                                <li class="list-group-item">
                                    <a href="{{ url($thread->path) }}">
                                        {{ $thread->title }}
                                    </a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                @endif
            </div>
        </ais-index>
    </div>
@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('header')
    <link href="/css/vendor/jquery.atwho.css" rel="stylesheet">
@endsection

@section('content')
    <thread-view :thread="{{ $thread }}" inline-template>
        <div class="container">
            <div class="row">
                <div class="col-md-8" v-cloak>
                    @include('threads._thread_content')

                    <replies @added="repliesCount++" @removed="repliesCount--"></replies>

                </div>
                <div class="col-md-4">
                     <div class="card">
                        <div class="card-body">
                            <p>
                                This thread was published {{ $thread->created_at->diffForHumans() }} by
                                <a href="#">{{ $thread->creator->user_name }}</a>, and currently has
                                <span v-text="repliesCount"></span> {{ str_plural('comment', $thread->replies_count) }}.
                            </p>
                            <p>
                                <subscribe-button :active="{{ json_encode($thread->isSubscribedTo) }}" v-if="signedIn"></subscribe-button>
                                <button class="btn btn-default"
                                        v-if="authorize('isAdmin')"
                                        @click="toggleLock"
                                        v-text="locked ? 'Unlock' : 'Lock' ">
                                </button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </thread-view>
@endsection